;(function() {

window.parts = function() {
	return [
		// Cells
		{
			id: 'uranium1',
			type: 'uranium',
			level: 1,
			title: 'Uranium Cell',
			base_description: '%single_cell_description',
			category: 'cell',
			cell_count: 1,
			pulse_multiplier: 1,
			base_cost: 10,
			base_ticks: 15,
			base_power: 1,
			base_heat: 1,
			cell_tick_upgrade_cost: 100,
			cell_tick_upgrade_multiplier: 8,
			cell_power_upgrade_cost: 500,
			cell_power_upgrade_multiplier: 8,
			cell_perpetual_upgrade_cost: 1000
		},
		{
			id: 'uranium2',
			type: 'uranium',
			level: 2,
			title: 'Dual Uranium Cell',
			base_description: '%multi_cell_description',
			category: 'cell',
			cell_count: 2,
			pulse_multiplier: 1,
			base_cost: 25,
			base_ticks: 15,
			base_power: 4,
			base_heat: 8
		},
		{
			id: 'uranium3',
			type: 'uranium',
			level: 3,
			title: 'Quad Uranium Cell',
			base_description: '%multi_cell_description',
			category: 'cell',
			cell_count: 4,
			pulse_multiplier: 1,
			base_cost: 60,
			base_ticks: 15,
			base_power: 12,
			base_heat: 36
		},
		{
			id: 'plutonium',
			type: 'plutonium',
			levels: 3,
			title: 'Plutonium Cell',
			base_description: '%single_cell_description',
			category: 'cell',
			base_cost: 1600,
			base_ticks: 150,
			base_power: 16,
			base_heat: 16,
			cell_tick_upgrade_cost: 16000,
			cell_tick_upgrade_multiplier: 8,
			cell_power_upgrade_cost: 80000,
			cell_power_upgrade_multiplier: 8,
			cell_perpetual_upgrade_cost: 160000
		},
		{
			id: 'thorium',
			type: 'thorium',
			levels: 3,
			title: 'Thorium Cell',
			base_description: '%single_cell_description',
			category: 'cell',
			base_cost: 256000,
			base_ticks: 1500,
			base_power: 256,
			base_heat: 256,
			cell_tick_upgrade_cost: 2560000,
			cell_tick_upgrade_multiplier: 8,
			cell_power_upgrade_cost: 12800000,
			cell_power_upgrade_multiplier: 8,
			cell_perpetual_upgrade_cost: 25600000
		},
		{
			id: 'seaborgium',
			type: 'seaborgium',
			levels: 3,
			title: 'Seaborgium Cell',
			base_description: '%single_cell_description',
			category: 'cell',
			base_cost: 40960000,
			base_ticks: 15000,
			base_power: 4096,
			base_heat: 4096,
			cell_tick_upgrade_cost: 409600000,
			cell_tick_upgrade_multiplier: 8,
			cell_power_upgrade_cost: 2048000000,
			cell_power_upgrade_multiplier: 8,
			cell_perpetual_upgrade_cost: 4096000000
		},
		{
			id: 'dolorium',
			type: 'dolorium',
			levels: 3,
			title: 'Dolorium Cell',
			base_description: '%single_cell_description',
			category: 'cell',
			base_cost: 6553600000,
			base_ticks: 150000,
			base_power: 65536,
			base_heat: 65536,
			cell_tick_upgrade_cost: 65536000000,
			cell_tick_upgrade_multiplier: 8,
			cell_power_upgrade_cost: 327680000000,
			cell_power_upgrade_multiplier: 8,
			cell_perpetual_upgrade_cost: 655360000000
		},
		{
			id: 'nefastium',
			type: 'nefastium',
			levels: 3,
			title: 'Nefastium Cell',
			base_description: '%single_cell_description',
			category: 'cell',
			base_cost: 1048576000000,
			base_ticks: 1500000,
			base_power: 1048576,
			base_heat: 1048576,
			cell_tick_upgrade_cost: 10485760000000,
			cell_tick_upgrade_multiplier: 8,
			cell_power_upgrade_cost: 52428800000000,
			cell_power_upgrade_multiplier: 8,
			cell_perpetual_upgrade_cost: 104857600000000
		},
		{
			id: 'protium',
			type: 'protium',
			levels: 3,
			title: 'Protium Cell',
			base_description: '%single_cell_description' + ' After being fully depleted, protium cells permanently generate 10% more power per depleted cell.',
			category: 'cell',
			experimental: true,
			erequires: 'protium_cells',
			base_cost: 167772160000000,
			base_ticks: 15000000,
			base_power: 16777216,
			base_heat: 16777216
		},

		// Energy
		{
			id: 'reflector',
			type: 'reflector',
			title: 'Neutron Reflector',
			base_description: 'Increases adjacent cell power output by %power_increase% for %ticks total pulses.',
			levels: 5,
			category: 'reflector',
			level: 1,
			base_cost: 50,
			cost_multiplier: 16,
			base_power_increase: 5,
			power_increase_add: 1,
			base_ticks: 60,
			ticks_multiplier: 16
		},
		{
			id: 'reflector6',
			type: 'reflector',
			title: 'Thermal Neutron Reflector',
			base_description: 'Increases adjacent cell power output by %power_increase% and heat output by %heat_increase% for %ticks total pulses.',
			category: 'reflector',
			experimental: true,
			erequires: 'heat_reflection',
			level: 6,
			base_cost: 5242800,
			base_power_increase: 5,
			base_heat_increase: 100,
			base_ticks: 6214560
		},
		{
			id: 'capacitor',
			type: 'capacitor',
			title: 'Capacitor',
			base_description: 'Increases the maximum power of the reactor by %reactor_power. Holds a maximum of %containment heat.',
			levels: 5,
			category: 'capacitor',
			level: 1,
			base_cost: 500,
			cost_multiplier: 32,
			base_reactor_power: 100,
			reactor_power_multiplier: 16,
			base_containment: 10,
			containment_multiplier: 8
		},
		{
			id: 'capacitor6',
			type: 'capacitor',
			title: 'Extreme Capacitor',
			base_description: 'Increases the maximum power of the reactor by %reactor_power. Holds a maximum of %containment heat. Heat is added to each unit equal to 50% of the power automatically sold by it.',
			category: 'capacitor',
			experimental: true,
			erequires: 'experimental_capacitance',
			level: 6,
			base_cost: 16777216000,
			base_reactor_power: 104857600,
			base_containment: 32768000
		},

		// Heat
		{
			id: 'vent',
			type: 'vent',
			title: 'Heat Vent',
			base_description: 'Lowers heat of itself by %vent per tick. Holds a maximum of %containment heat.',
			levels: 5,
			category: 'vent',
			level: 1,
			base_cost: 50,
			cost_multiplier: 16,
			base_containment: 128,
			containment_multiplier: 4,
			base_vent: 4,
			vent_multiplier: 4,
			location: 'cooling'
		},
		{
			id: 'vent6',
			type: 'vent',
			title: 'Extreme Vent',
			base_description: 'Lowers heat of itself by %vent per tick. Holds a maximum of %containment heat. Must consume power from the reactor at a rate of 100% of the heat removed from itself.',
			category: 'vent',
			experimental: true,
			erequires: 'vortex_cooling',
			level: 6,
			base_cost: 52428800,
			base_containment: 131072,
			base_vent: 4096,
		},
		{
			id: 'heat_exchanger',
			type: 'heat_exchanger',
			title: 'Heat Exchanger',
			base_description: 'Attempts to balance the heat between itself and adjacent components by percentage. Transfers up to %transfer heat per tick for each adjacent component. Holds up to %containment heat.',
			levels: 5,
			category: 'heat_exchanger',
			level: 1,
			base_cost: 200,
			cost_multiplier: 16,
			base_containment: 512,
			containment_multiplier: 4,
			base_transfer: 16,
			transfer_multiplier: 4,
			location: 'cooling'
		},
		{
			id: 'heat_exchanger6',
			type: 'heat_exchanger',
			title: 'Extreme Heat Exchanger',
			base_description: 'Attempts to balance the heat between itself, adjacent components and its entire row by percentage. Transfers up to %transfer heat per tick for each adjacent component. Holds up to %containment heat.',
			category: 'heat_exchanger',
			experimental: true,
			erequires: 'underground_heat_extraction',
			level: 6,
			base_cost: 209715200,
			base_containment: 524288,
			base_transfer: 16384,
		},
		{
			id: 'heat_inlet',
			type: 'heat_inlet',
			title: 'Heat Inlet',
			base_description: 'Takes %transfer heat out of each adjacent component and puts it into the reactor each tick.',
			levels: 5,
			category: 'heat_inlet',
			level: 1,
			base_cost: 200,
			cost_multiplier: 16,
			base_transfer: 16,
			transfer_multiplier: 4,
			location: 'cooling'
		},
		{
			id: 'heat_inlet6',
			type: 'heat_inlet',
			title: 'Extreme Heat Inlet',
			base_description: 'Takes %transfer heat out of each adjacent component and puts it into the reactor each tick. Has a range of %range squares.',
			category: 'heat_inlet',
			experimental: true,
			erequires: 'vortex_extraction',
			base_range: 2,
			level: 6,
			base_cost: 209715200,
			base_transfer: 16384,
		},
		{
			id: 'heat_outlet',
			type: 'heat_outlet',
			title: 'Heat Outlet',
			base_description: '%transfer heat is taken out of the reactor and put into each adjacent component.',
			levels: 5,
			category: 'heat_outlet',
			level: 1,
			base_cost: 200,
			cost_multiplier: 16,
			base_transfer: 16,
			transfer_multiplier: 4,
			location: 'cooling'
		},
		{
			id: 'heat_outlet6',
			type: 'heat_outlet',
			title: 'Extreme Heat Outlet',
			base_description: 'For each adjacent component %transfer is taken out of the reactor and put into the adjacent component. Has a range of %range squares.',
			category: 'heat_outlet',
			experimental: true,
			erequires: 'explosive_ejection',
			base_range: 2,
			level: 6,
			base_cost: 209715200,
			base_transfer: 16384,
		},
		{
			id: 'coolant_cell',
			type: 'coolant_cell',
			title: 'Coolant Cell',
			base_description: 'Holds %containment heat before being destroyed.',
			levels: 5,
			category: 'coolant_cell',
			level: 1,
			base_cost: 500,
			cost_multiplier: 16,
			base_containment: 2000,
			containment_multiplier: 16,
			location: 'cooling'
		},
		{
			id: 'coolant_cell6',
			type: 'coolant_cell',
			title: 'Thermionic Coolant Cell',
			base_description: 'Holds %containment heat before being destroyed. 50% of the heat added to this part is instantly converted to power and added to the generator.',
			category: 'coolant_cell',
			experimental: true,
			erequires: 'thermionic_conversion',
			level: 6,
			base_cost: 524288000,
			base_containment: 2097152000
		},
		{
			id: 'reactor_plating',
			type: 'reactor_plating',
			title: 'Reactor Plating',
			base_description: 'Increases maximum heat of the reactor by %reactor_heat.',
			levels: 5,
			category: 'reactor_plating',
			level: 1,
			base_cost: 200,
			cost_multiplier: 16,
			base_reactor_heat: 100,
			reactor_heat_multiplier: 8,
			location: 'cooling'
		},
		{
			id: 'reactor_plating6',
			type: 'reactor_plating',
			title: 'Charged Reactor Plating',
			base_description: 'Increases maximum heat and power of the reactor by %reactor_heat.',
			category: 'reactor_plating',
			experimental: true,
			erequires: 'micro_capacitance',
			level: 6,
			base_cost: 209715200,
			base_reactor_heat: 3276800
		},
		{
			id: 'particle_accelerator',
			type: 'particle_accelerator',
			title: 'Particle Accelerator',
			base_description: 'Generates Exotic Particles based on heat passing through the accelerator (maximum %ep_heat). If this part explodes it causes instant reactor meltdown. Holds a maximum of %containment heat.',
			levels: 5,
			category: 'particle_accelerator',
			level: 1,
			base_cost: 1000000,
			cost_multiplier: 1000,
			base_containment: 100,
			containment_multiplier: 1000000,
			base_ep_heat: 500000000,
			ep_heat_multiplier: 20000,
			location: 'cooling'
		},
		{
			id: 'particle_accelerator6',
			type: 'particle_accelerator',
			title: 'Black Hole Particle Accelerator',
			base_description: 'Generates Exotic Particles based on heat passing through the accelerator (maximum %ep_heat). If this part explodes it causes instant reactor meltdown. Holds a maximum of %containment heat. Actively draws %transfer heat from the reactor at the cost of 1 power per 1 heat.',
			category: 'singularity_harnessing',
			experimental: true,
			erequires: '',
			level: 6,
			base_cost: 100000000000000,
			base_containment: 100000000000000000000000000000000,
			base_ep_heat: 1600000000000000000000000000000
		}
	];
};
})();
